const express = require("express")
const Router = express.Router()
const tokenexpire = require('../middleware/blacklist')
const jsonwebtoken = require("../middleware/jsonwebtoken")
const {addtocart,viewcart,quantity,removecart} = require("../controller/cart")
Router.post('/addtocart/:productId',tokenexpire,jsonwebtoken,addtocart)
Router.get('/viewcart',tokenexpire,jsonwebtoken,viewcart)
Router.put('/quantity/:Id',tokenexpire,jsonwebtoken,quantity)
Router.delete('/removecart/:productId',tokenexpire,jsonwebtoken,removecart)
module.exports = Router